#!mast -x *.lock .index .ruby .yardopts bin data lib man share spec test *.md *.rdoc *.txt
.index
.ruby
lib/assay/rspec.rb
lib/rspecial/expect.rb
lib/rspecial/have.rb
lib/rspecial/matchers.rb
lib/rspecial/operatics.rb
lib/rspecial/should.rb
lib/rspecial.rb
lib/rspecial.yml
HISTORY.md
README.md
DEMOS.md
LICENSE.txt
